language: node_js
services:
  - mongodb
node_js:
  - v5
  - v4
  - '0.12'
  - '0.10'
# Need to add sleep for mongo - http://docs.travis-ci.com/user/database-setup/#MongoDB-may-not-be-immediately-accepting-connections
before_script:
  - sleep 15
